apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-sitesync
spec:
  selector:
    matchLabels:
      app: skupper-sitesync
  template:
    metadata:
      labels:
        app: skupper-sitesync
    spec:
      serviceAccount: skupper-sitesync
      containers:
      - name: skupper-sitesync
        image: nicepink/skupper-sitesync:latest
        args:
        - -configName
        - skupper-site
        - -configNamespace
        - ops
        - -loopDelay
        - '20'
        - -isInCluster
        - -loop
        resources:
          limits:
            memory: 64Mi
            cpu: 10m
